In [7]:
import numpy as np
import random 
import time

In [166]:
# Q(st, sa) + alpha [rt+1 + epsilon max Q(st+1, a) - Q(st-at)]
# step t, agent st, agent moves: st+1, action: at

In [56]:
# Q-table s x a = 6 x 2
state_size = 6
action_size = 2
move_cost = 0.01

# Q-table aand values initialized to zero
q_table = np.zeros((state_size,action_size))
print(q_table)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [71]:
alpha = 0.1 #learning rate
epsilon = 1 #discount factor
gamma = 0.8 #discount rate

reward = [-1, 0, 0, 0, 0, +1]

#external loop, the following is just an episode, make a loop for more episodes here
max_episodes = 100
j=0

while j < max_episodes:
  state = 2
  maxIteration=100
  i = 0
  j = j+1
  while i < maxIteration:
    if(state==0 or state==5):
      break
    #randomly choose an action - left:0 - right:1 -
    rnd = random.randint(0, 1)
    if rnd == 0:
      new_state = state -1
    else:
      new_state = state +1
    i = i+1

  # update Qtable
    q_table[state, rnd] = q_table[state, rnd] + alpha * ((reward[new_state]-move_cost + gamma * max(q_table[new_state] - q_table[state, rnd])))
    state=new_state
print(q_table)

[[ 0.          0.        ]
 [-1.29970234  1.06125177]
 [ 1.01614609  1.10318187]
 [ 1.05645784  1.15231885]
 [ 1.11110697  1.20113011]
 [ 0.          0.        ]]


In [70]:
#greedy algorithm 

alpha =0.3 # the learning rate, 0 agent learns nothing, 1 learns recent information
gamma = 0.8 # the discount factor, determines of future rewards

maxEpisode = 100
cost = 0.1
reward=[-1,0,0,0,0,+1]
maxIteration = 100
maxEpisode = 100

Q_table = np.zeros((6,2))

def greedy(array, state): 
  if array[state, 0] > array[state,1] :
    return 0
  else:
    return 1
  
j = 0
while j < maxEpisode:
  epsilon = 1
  state = 2
  j = j+1
  i=0

  while i < maxIteration: # 0 < 100    
    r = np.random.uniform(0,1)    
    i= i+1
    
    if (state == 0 or state == 5): 
      break
      
    if r < epsilon: #Exploration
      action = np.random.randint(0,2)
          
    elif r>=epsilon : # Exploitation
      action=greedy(Q_table, state)
    
    if action == 0:
      #print('right')
      new_state = state + 1
    elif action == 1: 
      #print('left')
      new_state = state - 1 
    epsilon -=0.01

    Q_table[state,  action] = Q_table[state, action] + alpha * ((reward[new_state]-cost + gamma * max(Q_table[new_state] - Q_table[state, action])))
    state=new_state

print(Q_table)

[[ 0.          0.        ]
 [ 0.74999047 -1.37499739]
 [ 0.87499595  0.62498259]
 [ 0.99999774  0.74999114]
 [ 1.12499929  0.87493567]
 [ 0.          0.        ]]


In [76]:
# 2D grid
# Q-table s x a = 3x4 x 4
n_rows=3
n_cols = 4
action_size = 4
move_cost = 0.04

# Q-table aand values initialized to zero
q2_table = np.zeros((12,action_size))
print(q2_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [77]:
alpha = 0.5 #learning rate
epsilon = 1
gamma = 0.7 #discount rate
move_cost = 0.04

reward = [(0, 0, 0, +1),
          (0, 0 , 0, -1),
          (0, 0, 0, 0)]

n_rows = len(reward)
n_cols = len(reward[0])

#start position
start_pos = (2,0)
win_pos = (0,3)
lose_pos = (1,3)

#randomly choose an action - left:0 - right:1 - up: 2 - down:3 -

maxEpisodes=100
maxIteration=100
f=0
while f < maxEpisodes:
  #restart from start position
  pos=start_pos
  e=0
  f=f+1
  while e < maxIteration:
    if(pos==win_pos or pos==lose_pos):
      break 
    move = random.randint(0, 3)
    #check if it can move in the direction or not
    if (pos[1]>0 and move==0): #left
      new_pos = (pos[0], pos[1]-1)
    elif (pos[1]<3 and move==1): #right
      new_pos = (pos[0], pos[1]+1)
    elif (pos[0]>0 and move==2): #up
      new_pos = (pos[0]-1, pos[1])
    elif (pos[0]<2 and move==3): #down
      new_pos = (pos[0]+1, pos[1])
    else: #estremo
      continue 
    if new_pos==(1,1): # if it goes into the black box, dont update pos but choose another move
      continue
    e = e+1

    # update Qtable
    state = pos[0]*n_cols+pos[1]
    new_state = new_pos[0]*n_cols+new_pos[1]
    q2_table[state, move] = q2_table[state, move] + alpha * ((reward[new_pos[0]][new_pos[1]]-move_cost + gamma * max(q2_table[new_state] - q2_table[state, move])))
    pos=new_pos

print(q2_table)

[[ 0.          1.25714215  0.          1.14285432]
 [ 1.19999754  1.31428538  0.          0.        ]
 [ 1.25713947  1.3714285   0.          1.25687057]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          1.19999883  1.08571267]
 [ 0.          0.          0.          0.        ]
 [ 0.         -1.48570571  1.31427567  1.19968596]
 [ 0.          0.          0.          0.        ]
 [ 0.          1.14281675  1.14285586  0.        ]
 [ 1.08571283  1.1999739   0.          0.        ]
 [ 1.1428189   1.14274186  1.2571242   0.        ]
 [ 1.19992246  0.         -1.48571329  0.        ]]
