In [38]:
!pip install numpy --quiet 
!pip install torch --quiet 

!pip install gym --quiet
!pip install pyglet --quiet
!pip install seaborn --quiet
!pip install ipympl --quiet


You should consider upgrading via the '/Users/taylorlucero/opt/anaconda3/bin/python3 -m pip install --upgrade pip' command.
You should consider upgrading via the '/Users/taylorlucero/opt/anaconda3/bin/python3 -m pip install --upgrade pip' command.
You should consider upgrading via the '/Users/taylorlucero/opt/anaconda3/bin/python3 -m pip install --upgrade pip' command.
You should consider upgrading via the '/Users/taylorlucero/opt/anaconda3/bin/python3 -m pip install --upgrade pip' command.
You should consider upgrading via the '/Users/taylorlucero/opt/anaconda3/bin/python3 -m pip install --upgrade pip' command.
You should consider upgrading via the '/Users/taylorlucero/opt/anaconda3/bin/python3 -m pip install --upgrade pip' command.


# To Do 
Store data to increase Size of Data 
Improve Architecture RNN 
*Apply Greedy epsilon*
LSTM 
Visualize Accuracy 
Visualize Loss
Add in the pictures of the changes of the ram 
Look at the accuracy and its changes * increasing the learning rate changes the accuracy, but it stay withing a set range*
θ target  does not update through backpropagation.


In [39]:
#Lucky if these work
!pip install gym\[atari\] --quiet 
!pip install atari-py --quiet 

You should consider upgrading via the '/Users/taylorlucero/opt/anaconda3/bin/python3 -m pip install --upgrade pip' command.
You should consider upgrading via the '/Users/taylorlucero/opt/anaconda3/bin/python3 -m pip install --upgrade pip' command.


In [40]:
#%matplotlib widget
import gym 
from gym.utils.play import play 
import atari_py
import imageio
import numpy as np
import torch
import torch.nn
import torch.optim
import torch.autograd
import pyglet
import math
from tqdm import tqdm
import torch.optim
import matplotlib
import matplotlib.pyplot as plt
from itertools import count
import random
from collections import namedtuple
from collections import deque
import IPython
import pandas as pd
import seaborn as sns

# Called Function 
Gathers Information During playing 

(Information Gathering) 

In [4]:
"""
Creates a function that stored the information from the played game
# observations are an array of length 128
"""
observation_list = []
action_list= []
reward_list = [] 
prev_observation_list = []

def Transition(observation, prev_observation, action, reward, done, info):
    #print("action = ", action, "observation",observation, " reward = ", reward, "done = ", done)
    # ^^ commented out as I know it works
    #observation_ram = env.unwrapped._get_ram()
    global observation_list
    global action_list
    global reward_list
    global prev_observation_list
    
    
    
    action_list = np.append(action_list, action)
    #observation_list=np.append(observation_list, observation)
    observation_list += [observation]
    prev_observation_list+=[prev_observation]
    reward_list=np.append(reward_list, reward )
    

        

    
   # print(observation)
   # print(action)
    
    

Structures the data into a usable format

In [5]:
env =gym.make('DemonAttack-ram-v0')
env.reset()


gym.utils.play.play(env, zoom=3, fps=13, callback=Transition)


env.close()
# Play to understand controls

# Understanding and structuring 
Collecting, understanding, and structuring the collected information 

In [8]:
print("action space")
print(env.action_space)
# Discrete 6 - 6 possible actions [0,6]

# rewards +10 everytime demon killed

action space
Discrete(6)


In [9]:
print("observation space")
print(env.observation_space)
# n- dimensional box - 3 numbers

observation space
Box([0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255], (128,), uint8)


In [10]:
print("observation ", len(observation_list))
print("prev_observation", len(prev_observation_list)) # past observation
print("action",len(action_list))
print("reward",len(reward_list))
# 10624

observation  43
prev_observation 43
action 43
reward 43


In [11]:
print(observation_list[1])
print(prev_observation_list[0])
print(action_list[0])
print(reward_list[0])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   5   0
   0   0   0   3 245   2  44   0   4   0   1   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   1   1  17   1   0   0   0
   0   0   0   0   0   7   0  75   0  51   0  30   0  30  90 149 134  90
   0   0   0   0 255 174  31   0   0 255  44  86  76  87  58  22   1 150
   0 154   0 100  31 100  31 100  31 100  31 100  31 128  31 255   1 128
   4   0   3   0   0 255   3   3   0   0   0 140   0 245   0   0  36  28
 135  19]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   5   0
   0   0   0   3 245   2  44   0   4   0   1   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   1   1  17   1   0   0   0
   0   0   0   0   0   7   0  75   0  51   0  30   0  30  90 149 134  90
   0   0   0   0 255 174  31   0   0 255  44  86  76  87  58  22   1 150
   0 154   0 100  31 100  31 100  31 100  31 100  31 128  31 255   1 128
   4   0   3   0   0 255   3   3   0   0 

In [12]:
len(observation_list)#[[], [], []]
print(len(prev_observation_list))
print(action_list.shape) #[_,_,_]
print(len(action_list))
print(reward_list.shape)
print(type(observation_list[0][5]))


43
(43,)
43
(43,)
<class 'numpy.uint8'>


In [13]:
#the difference  between the latest observation and the prev
diff = np.subtract(observation_list, prev_observation_list)
print(diff)

[[  1 171   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [14]:
#the difference between the latest observations and the previous 
new_diff = np.subtract(prev_observation_list, observation_list)
print(new_diff)

[[255  85   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


# Training Phase

In [41]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

In [42]:
## This needs to be fixed and updated
# module or custom set formatting

class DQN(torch.nn.Module):
    def __init__(self,observation):
        super(DQN,self).__init__()
        self.net= torch.nn.Sequential(
            torch.nn.Linear(128,768),
            torch.nn.ReLU(),
            torch.nn.Linear(768, 1536),
            torch.nn.ReLU(),
            torch.nn.Linear(1536, 6),
            #torch.nn.Softmax()
            #torch.nn.Flatten(256, 1)

        ).to(device)
        
    def forward(self, inputs):
        #print(inputs)
        inputs = self.net(inputs)
        new_shape = (len(inputs))
        inputs = inputs.view(new_shape)
        return inputs
        
        


# Hyperparameters and utilities  

This cell instantiates our model and its optimizer, and defines some utilities:


#Training loop

Optimize the model functions that performs a single step of the optimization. It first samples a batch, concatenates all tensors into a single one, and combines them into our loss. By Def we set V(s) = 0 if is a terminal state. We also use a target network to compute V(s) for added stability. The target network has its weight kept frozen most of the time, but is updated with the policy network's wieghts every. This is usually a set number of steps we shall use episodes. 

# Main Training loop

In [43]:
# Random Game 

total_rew = 0
env = gym.make('DemonAttack-ram-v0')
env.reset()

while True:
    env.render()
             # take an initial action 
    obs,reward,done,info=env.step(env.action_space.sample())
    total_rew = total_rew + reward

    if reward != 0:
        print("reward: ", reward)
        print("total reward:,", total_rew)
        print("Number of", info['lives'])
        number=info['lives']

        
    
env.close()
#140
#175
#235
#375
#100
#60
#250

reward:  10.0
total reward:, 10.0
Number of 4
reward:  10.0
total reward:, 20.0
Number of 3
reward:  10.0
total reward:, 30.0
Number of 2
reward:  10.0
total reward:, 40.0
Number of 2
reward:  10.0
total reward:, 50.0
Number of 2
reward:  10.0
total reward:, 60.0
Number of 2
reward:  10.0
total reward:, 70.0
Number of 1


KeyboardInterrupt: 

In [44]:
"""def select_action(self, state, policy_net):
        #global policy_net
        E_rate = self.strategy.exploration_rate(self.step)
        self.step += 1

        if E_rate > random.random():
            action=random.randrange(self.n_actions) #random action from Epsilon  
            return torch.tensor([action]).to(device)
    
        else:
            with torch.no_grad():
                return policy_net(state).argmax(dim=1).to(device) #exploitation"""
    
    
def exploration_rate(step):
        return end_Eps + (start_Eps - end_Eps) * math.exp(-1. * step * decay_Eps)
        

In [45]:
Experience = namedtuple(
    'Experience',
    ('observation', 'action', 'reward', 'pre_observation', 'diff_observation')
)

In [46]:
def pull_tensors(exp):
    memory = []
    experience_tracked = 0 
    storage = 100000
    
    if len(memory) < storage:
            memory.append(exp)
    else:
        memory[experience_tracked % storage] = exp
        experience_tracked += 1
        
    for x in exp:      
        batch = Experience(*zip(x))
        #print(len(batch))
        #print("this",batch) 

        tensor1= torch.cat(batch.observation)
        #print(batch.action[0].view(-1))
        tensor2= torch.cat((batch.action[0].view(-1), torch.zeros(5)))
        tensor3= torch.cat((batch.reward[0].view(-1), torch.zeros(5)))
        tensor4= torch.cat(batch.pre_observation)
        tensor5= torch.cat(batch.diff_observation)
    
    return (tensor1, tensor2, tensor3, tensor4, tensor5)

In [47]:
obs,rew,done,info=env.step(env.action_space.sample() )
print(type(obs))

<class 'numpy.ndarray'>


In [48]:
policy_net = DQN(torch.from_numpy(obs)).to(device)
target_net = DQN(torch.from_numpy(obs)).to(device)

In [49]:
criterion = torch.nn.SmoothL1Loss()

In [50]:
#test
def Obs2Act(observation):
    pred_action=target_net(observation.float())
    pred_action=pred_action.argmax()
    return pred_action

In [51]:
Episodes = 200
start_Eps = 1
end_Eps = 0.01
decay_Eps = 0.001
step = 0
storage= []
diff_obs_list = []
batch_size = 128
counter = 0 
gamma = 0.5
update = 10
e_loss, e_acc = [], []
running_loss = 0
running_accuracy = 0
e=0
lr=0.9
lives=[]

target_net.load_state_dict(policy_net.state_dict())
target_net.eval()

#criterion = torch.nn.SmoothL1Loss()

optimizer = torch.optim.Adam(policy_net.parameters(), lr=0.01)

episode_list=[]
while e in range(Episodes):
    print(e)
    stage = 0 
    total_rew = 0
    env = gym.make('DemonAttack-ram-v0')
    env.reset()
    obs,rew,done,info=env.step(env.action_space.sample() )
    
    for x in count():
        
        E_rate = exploration_rate(step)
        step += 1

        if E_rate > random.random():
            action = random.randrange(0,6)
            #print("exploration",action)
            #random action from Epsilon  
        else:
            with torch.no_grad():
                #print(torch.from_numpy(obs))
                #print((type(obs)))
                action = policy_net(torch.from_numpy(obs).float()).argmax().item()
                #print("exploitation",action)
                #.argmax(dim=1) #exploitation
       
    #### Runs
        pre_obs = obs
        
        #if isinstance(action, int):
            #obs, reward, done, info = env.step(action)
        #else:
            #print(action)
            #obs, reward, done, info = env.step(action.argmax())
        
        #print(obs)
        #Transition(observation, prev_observation, action, reward, done, info):
        
        #Transition(obs, pre_obs, action, reward, done, info)
        diff_obs = np.subtract(obs, pre_obs)
        #print('subtarct',action)
        x = Experience(torch.from_numpy(obs), torch.as_tensor(action), torch.as_tensor(reward), torch.from_numpy(pre_obs),torch.from_numpy(diff_obs))
        storage.append(x)
        #print(memory)

        
        if len(storage) >= batch_size:
            observation, actions, rewards, pre_observation,diff_observation = pull_tensors(storage)
            
            #print("obs",observation)
            #print("actions",actions)
            #print("rewards",rewards)
            #print("pre",pre_observation)
            #print("diff",diff_observation)
            
            # Q_Table 
            #print(torch.max(actions).unsqueeze(-1).item())
            #print("action",actions.type(torch.int64).unsqueeze(-1))
            
            Current_q = policy_net(diff_observation.float())#.gather(dim=0, index=actions.type(torch.int64))
            #print(Current_q)
            #final_state = n_states.flatten(start_dim=1).max(dim=1)[0].eq(0).type(torch.bool)
            Next_q = target_net(observation.float())
           # print(Next_q)
            #Next_q = Next(target_net, observation)
            Target_q = (Next_q * gamma) + torch.max(rewards).item()
            
            #print(Target_q)
            
           # qval.current(policy_net, observations,actions) #tenso  
           # Next_q = qval.next(target_net, n_states)
            #Target_q = (Next_q * gamma) + rewards
            #print(batch)
            #observations, actions, pre_observations, rewards = pull_tensors(exp)
            # once target_net is implemented use loss
            #print(Current_q)
            
            #print(Target_q)
            #print(Target_q.unsqueeze(1))
        
            loss = criterion(Current_q, Target_q)
            
            running_loss += loss.item()
            running_accuracy += (Next_q.argmax() == actions).sum().item()
            # zero out gradient: set gradients in policy net to zero 
            
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            
            while done==False:
                e_loss.append(running_loss/Episodes)
                e_acc.append(running_accuracy/Episodes)
                
                env.render()
                action = Obs2Act(torch.from_numpy(obs).float())
                obs,reward,done, info = env.step(action)
                total_rew = total_rew + reward 
                lives.append(number)
                number=info['lives']

                if reward != 0:
                    print("reward: ", reward)
                    print("total reward:,", total_rew)
                    print(number)
                    
                if number==number or number>=number:
                    continue
                else:
                    print("died", reward-10)
                            
                    
            else:
                e +=1
                break

                
    
        if e % update == 0:
            target_net.load_state_dict(policy_net.state_dict())
    
            
    else:
        env.close()
        #while True:
            #env.render()
             # take an initial action 
            #action = Obs2Act(torch.from_numpy(obs).float())
            #obs,rew,done, info = env.step(action)
            #total_rew = total_rew + rew

            #if rew != 0:
               # print("reward: ", rew)
                #print("total reward:,", total_rew)

        



#It will stop at the end of a set of 21 games. In the loop, you need to predict, from obs, 
#the action to be performed at the next iteration. Observe the scores for several games.

#205
#250
#160

0
reward:  10.0
total reward:, 10.0
4
reward:  10.0
total reward:, 20.0
4
reward:  10.0
total reward:, 30.0
4
reward:  10.0
total reward:, 40.0
4
reward:  10.0
total reward:, 50.0
4
reward:  10.0
total reward:, 60.0
4
reward:  10.0
total reward:, 70.0
3
reward:  10.0
total reward:, 80.0
3
reward:  10.0
total reward:, 90.0
3
reward:  10.0
total reward:, 100.0
2
reward:  10.0
total reward:, 110.0
2
reward:  10.0
total reward:, 120.0
2
reward:  10.0
total reward:, 130.0
2
reward:  10.0
total reward:, 140.0
2
reward:  10.0
total reward:, 150.0
1
reward:  10.0
total reward:, 160.0
1
reward:  15.0
total reward:, 175.0
1
reward:  15.0
total reward:, 190.0
1
reward:  15.0
total reward:, 205.0
1
reward:  15.0
total reward:, 220.0
1
reward:  15.0
total reward:, 235.0
1
reward:  15.0
total reward:, 250.0
1
reward:  15.0
total reward:, 265.0
1
reward:  15.0
total reward:, 280.0
1
reward:  15.0
total reward:, 295.0
2
reward:  15.0
total reward:, 310.0
1
reward:  15.0
total reward:, 325.0
1
1
reward

KeyboardInterrupt: 

In [69]:
#e_acc =converter_tensor_to_df(e_acc)
#print(e_acc)



In [52]:
e_acc=pd.DataFrame(e_acc, columns = ["Acc"])
e_acc.head()

Acc
0  0.0
1  0.0
2  0.0
3  0.0
4  0.0

In [53]:
e_loss=pd.DataFrame(e_loss, columns = ["Loss"])
e_loss.head()

Loss
0  0.007888
1  0.007888
2  0.007888
3  0.007888
4  0.007888

In [ ]:
sns.lineplot(data=e_loss, palette=["blue"])
sns.lineplot(data=e_acc, palette=["orange"])
plt.show()

In [65]:
#test
def Obs2Act(observation):
    pred_action=target_net(observation.float())
    pred_action=pred_action.argmax()
    return pred_action


The learning rate is a tuning parameter in an optimization algorithm that determines the step size at each iteration while moving toward a minimum of a loss function.
For reinforcement learning it refers to how much the model learns. If for example the model has an alpha of 0 then the Q-values won’t update and nothing is learned, however, on the other hand if alpha is set to 0.9 then it will learn rapidly.  It terms of this program of Demon attack, changing the learning rate improved how fast it learned a specific move. On one when firing it fired very well,  going up to scores of 940 to 1635, although the agent itself doesn’t move. If initial, movements are a change in lateral position then the agent has tendency to move right or left in attempts to avoid shooting. With a lower rate at about .01  it takes more episodes for the agent to improve and maximize rewards. I tried implementing a punishment whenever the agent dies providing a negative reward in an attempt to help the agent learn to avoid the lasers. With the alpha trying to minimize the loss function of the smooth l1 loss certain episodes will drastically especially when the learning is high, this because it takes a larger step downward on the curve to minimize the gradient. A larger learning however has the downside of causing divergence faster, as the step could over shoot the minimum. With DQN a single network is not as stable, hence the division of the policy network and the target network. The target network focuses Q(s’, a’) in the bellman equation. The second Q-values provided by this network are used to back propagate through and train the main network. This is to improve stability of the network. In this notebook I, attempted to freeze the policy and have the target backprop through the policy network. 